### ISSUE TITLE
Is it possible maintain tags in rails admin?

### ISSUE THREAD

**Issue by atusoft** [kryzhovnik/rails_admin_tag_list#12]
For example,  create a new item in Navigation, then list all tag to right part of page.

**Comment by kryzhovnik** [comment]
Sorry for silence.
If it's still relevant to you, explain please what do you mean by maintaining tags.

**Comment by UlfR** [comment]
@kryzhovnik seems for me 'maitain' mean: view/create/edit/delete as standard model, plus view all tagged models for tag

**Comment by kryzhovnik** [comment]
In that case, no. It doesn't allow to maintain tags as detached instances.
Essentially, this plugin has only one feature: let RailsAdmin to know about `tag_list` (`*_list`) field of the target model.
