### ISSUE TITLE
autocomplete and suggestions work only with field name tag

### ISSUE THREAD

**Issue by fmh** [kryzhovnik/rails_admin_tag_list#16]
autocomplete and suggestions work only with field name "tag" not with another , for example with "skill"

my code
`````ruby
acts_as_taggable_on :skills

  rails_admin do
    fields_of_type :skill_list do
      partial 'tag_list_with_suggestions'     
    end
  end
``````

**Comment by kryzhovnik** [comment]
`fields_of_type` sets options for each field of specific type (eg. tag_list). Use `field` to set options for a specific field.

    config.model Player do
      edit do
        field :tag_list # default partial

        field :skill_list do  # custom partial
          partial 'tag_list_with_suggestions'     
        end
      end
    end

**Comment by fmh** [comment]
thx, work now
