### ISSUE TITLE
rubygems.org version out of date

### ISSUE THREAD

**Issue by hashwin** [kryzhovnik/rails_admin_tag_list#17]
https://rubygems.org/gems/rails_admin_tag_list/

The latest version on rubygems seems to have been released on October 16, 2012, and does not include the latest changes for rails_admin, and breaks with a Rails 4 app.

Currently fixed by putting this in the Gemfile:
gem 'rails_admin_tag_list', git: 'git@github.com:kryzhovnik/rails_admin_tag_list.git'

It would be nice to have this updated on rubygems.org.

**Comment by Blackening999** [comment]
+1

**Comment by kryzhovnik** [comment]
[done](https://rubygems.org/gems/rails_admin_tag_list/versions/0.2.0)
