### ISSUE TITLE
Strongly need Rails 5 support

### ISSUE THREAD

**Issue by Blackening999** [kryzhovnik/rails_admin_tag_list#19]
It's a blocker for my project :(

**Comment by kryzhovnik** [comment]
What's problem with rails 5?
I've just created new project with rails 5, rails_admin 1.0.0.rc and last release of this gem and it's seems all right.
Could you provide more info?

**Comment by Blackening999** [comment]
@kryzhovnik Well it's weird, but I have just removed the gem, upgraded to Rails 5 and enabled it back and it seems to work. At least no complains.
