### ISSUE TITLE
undefined method `ratl_suggestions'

### ISSUE THREAD

**Issue by dedman** [kryzhovnik/rails_admin_tag_list#20]
Hey guys, 

Firstly thank you for this gem!

I'm having a little trouble with it. I'm running rails_admin 1.0.0, with rails 5.0.0.1. 

When I add this to the rails admin model config block

```
edit do
  fields_of_type :tag_list do
     partial 'tag_list_with_suggestions'
  end
end
```

I get an error saying "undefined method `ratl_suggestions'" from line 3 of the _tag_list_with_suggestions.html.haml partial.

Anyone know what I'm doing wrong? 

Thanks

**Comment by terry90** [comment]
Same here

**Comment by dedman** [comment]
Thanks @terry90 worked for me.

**Comment by adamlutz** [comment]
thanks much @terry90!  worked like a charm

**Comment by kryzhovnik** [comment]
Fixed in [00d20e975b0e5b85928ea7eda81f11f902081cdc](https://github.com/kryzhovnik/rails_admin_tag_list/commit/00d20e975b0e5b85928ea7eda81f11f902081cdc)

**Comment by dedman** [comment]
Thanks @kryzhovnik

**Comment by drubin** [comment]
@kryzhovnik thanks for fixing it. Any chance we can release a new version of this as a gem?
