### ISSUE TITLE
N+1 queries in list view

### ISSUE THREAD

**Issue by jamesfzhang** [kryzhovnik/rails_admin_tag_list#21]
Hi, thanks for creating this gem, it saved me a lot of time!

I wanted to add the `tag_list` field to the list view of the admin dashboard, so that I know which items still require to be tagged. I noticed that this causes a lot of n+1 queries. What's the best way to solve this problem? Thanks!

<img width="1437" alt="screen shot 2016-11-07 at 2 43 44 pm" src="https://cloud.githubusercontent.com/assets/2057670/20079224/9c77d4c8-a4f8-11e6-96b3-588bc3693685.png">

**Comment by kryzhovnik** [comment]
Sorry for my absence.

I've just checked the possibilities. It's required to much hacking to fix the issue. Btw I don't think N+1 problem is a huge problem in context of admin panel.
