### ISSUE TITLE
Rails Admin not registering field type. Am I missing something ?

### ISSUE THREAD

**Issue by bhushangahire** [kryzhovnik/rails_admin_tag_list#22]
undefined method `properties' for nil:NilClass

![image](https://cloud.githubusercontent.com/assets/8351/23050454/0f8907e6-f488-11e6-885b-b7f6d25fc07c.png)

` config.model 'Contact' do
    edit do
      fields_of_type :tag_list do
        partial 'tag_list_with_suggestions'
        # the option sets max count of suggestions (default is 100); set -1 to abolish the limit
        ratl_max_suggestions 10
      end
    end
#Contact Model
attr_accessible :tag_list
acts_as_taggable`

**Comment by kryzhovnik** [comment]
Sorry for my absence. If the issue is still relevant for, check the gem's last version.
