### ISSUE TITLE
Tag suggestion length not easily configurable

### ISSUE THREAD

**Issue by brookr** [kryzhovnik/rails_admin_tag_list#6]
Thanks for the handy RA extension! I'm using it in my app, and wishing I could set the number of suggestions that show in the edit view. I'd be happy to help out and contribute something, but I can think of a few different ways of doing this, and wanted to touch base to see if it's something you'd be interested in pulling. Any opinions about the best way to set up a config option?

**Comment by kryzhovnik** [comment]
Added `ratl_max_suggestions` config option
